name: Pytest Unit Tests

on:
  push:
    branches: [ main ]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.2']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
        
      - name: Install Dependencies For main Module
        run: |
          cd src/backend/main
          pip install -r requirements.txt
        
      - name: Run Unit Tests
      
        run: |
          set -e
          # get parent folder
          DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
          PARENT_DIRECTORY="${DIR%/*}"
          # go to parent folder
          cd ${PARENT_DIRECTORY}
          python -m pytest --import-mode=append src/backend/tests/
          
